// Code generated by "stringer -type=Severity"; DO NOT EDIT.

package logger

import "fmt"

const _Severity_name = "L_EMERGL_ALERTL_CRITL_ERRL_WARNINGL_NOTICEL_INFOL_DEBUG"

var _Severity_index = [...]uint8{0, 7, 14, 20, 25, 34, 42, 48, 55}

func (i Severity) String() string {
	if i < 0 || i >= Severity(len(_Severity_index)-1) {
		return fmt.Sprintf("Severity(%d)", i)
	}
	return _Severity_name[_Severity_index[i]:_Severity_index[i+1]]
}
