version: '3'
services:

  web:
    build: .
    ports:
     - "8080:8080"
    networks:
      - internal
    image: "go-archetype-project"
    depends_on:
      - db
    environment:
      - TYPES=game,server,payment


  db:
    image: postgres
    networks:
      - internal
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=xxx
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  internal:
    driver: bridge

volumes:
  postgresql:
  postgresql_data: