POST http://localhost:8080/update-balance HTTP/1.1
Content-Type: application/json
Source-Type: client

{"state": "win", "amount": "10.15", "transactionId": "some generated identificator - 1"}

###

POST http://localhost:8080/update-balance HTTP/1.1
Content-Type: application/json
Source-Type: game

{"state": "lost", "amount": "1.15", "transactionId": "some generated identificator - 2"}

###

POST http://localhost:8080/update-balance HTTP/1.1
Content-Type: application/json
Source-Type: game

{"state": "lost", "amount": "-1.15", "transactionId": "some generated identificator - 3"}

###

POST http://localhost:8080/update-balance HTTP/1.1
Content-Type: application/json
Source-Type: game

{"state": "lost", "amount": "-10", "transactionId": "some generated identificator - 4"}

###
